### PR TITLE
Massive update and improvement

### PR DESCRIPTION
**Pull request by titaniummachine1**
some important changes
visual update for path visualization nwo follows player
repathing fixed and improved
added movement bypass to walk while script is active for debugging.
fixed msot of the pathign problems
fixed the movement breakign the pathing
fixed the problem where movign has made algoritm to remove all nodes

### CODE REVIEW

**Comment by titaniummachine1** [comment]
also jsut added update for navigation lua so it will automaticly generate navmesh for any map without any user input

**Comment by rosne-gamingyt** [comment]
> also jsut added update for navigation lua so it will automaticly generate navmesh for any map without any user input

When I can test this, I will merge it

**Comment by titaniummachine1** [comment]
surely

**Comment by titaniummachine1** [comment]
now working on subnode system but it keeps braking so its jsut mostly improvements to code and stil need to add
system wehre it will reload nav file if it gets lost

**Comment by rosne-gamingyt** [comment]
One thing, you added main.lua twice, delete the one not in Lmaobot

**Comment by titaniummachine1** [comment]
done

**Pull request merged**
