### PR TITLE
unstuck fix

### PR DESCRIPTION
**Pull request by titaniummachine1**
unstuck fix 
small fixes and improvements to prevent getting stuck

### CODE REVIEW

**Comment by titaniummachine1** [comment]
also added bunnyhop logic so it will juse jump when on ground until it finds way to get unstuck.

**Comment by titaniummachine1** [comment]
also added remove node for navigation lua as main lua needs it to work right

**Comment by titaniummachine1** [comment]
fixed payload

**Comment by titaniummachine1** [comment]
fixed problem with pathfinding on stairs as range 22 for block distance to think its been aproached was too clsoe and staris and ranmps were not gettign good distance enough to allow smooth movement

added followbot
simple tho

**Comment by rosne-gamingyt** [comment]
https://github.com/RosneBurgerworks/lmaobox-navbot/commit/6cdecc68aa98ad0b14039f03c1dc4a4ea264a691

**Pull request closed without merging**
