### PR TITLE
visual update

### PR DESCRIPTION
**Pull request by titaniummachine1**
fixe issues and stuff too

### CODE REVIEW

**Comment by titaniummachine1** [comment]
image

**Comment by titaniummachine1** [comment]
now it remvoes path that has been walked on

**Comment by rosne-gamingyt** [comment]
> now it remvoes path that has been walked on

why did you add another main.lua

**Comment by titaniummachine1** [comment]
> > now it remvoes path that has been walked on
> 
> why did you add another main.lua

what?

**Comment by titaniummachine1** [comment]
sorry now it should work fine

**Comment by rosne-gamingyt** [comment]
already merged https://github.com/RosneBurgerworks/lmaobox-navbot/commit/2972dd225d487534a3ea8d0882658da2bf27048b

**Pull request closed without merging**
